#Programming assignment week3: Caching the Inverse of a Matrix



# 1) makeCacheMatrix creates a "special matrix"
#       special matrix is a list of functions setting and getting values 
#       for the matrix and its reverse in cache
# 2) cacheSolve computes inverse of "special matrix" generated by makeCacheMatrix - 
#       if the reverse has already been calculated(and the matrix is not changed) - 
#       then cacheSolve should retrieve inverse from cache




# 1) function creates a 'special matrix' object that can cache its inverse

makeCacheMatrix <- function(x=matrix()){
        
        inverse <- NULL
        set <- function(y) {
                x <<- y
                inverse <<- NULL
        }
        get <- function() x
        setinverse <- function(i) inverse <<- i
        getinverse <- function() inverse
        list(set = set, get = get,
             setinverse = setinverse,
             getinverse = getinverse)
        
        
}



#  2) function returns a matrix that is inverse to x (x is 'special matrix')
#       if inverse matrix has been calculated before
#       -> cacheSolve will retrieve it from cache

cacheSolve <- function(x,...){
        
        inverse <- x$getinverse()
        if(!is.null(inverse)) {
                message("getting cached data")
                return(inverse)
        }
        data <- x$get()
        inverse <- solve(data, ...)
        x$setinverse(inverse)
        inverse 
}